name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: macOS-10.15
    steps:
    - uses: actions/checkout@v2.3.2
    - name: Run tests
      env: 
        DEVELOPER_DIR: /Applications/Xcode_12.app
      # Normally would use `swift test` but there's a bug related to SPM package resources, so using xcodebuild as a workaround
      # https://forums.swift.org/t/swift-5-3-spm-resources-in-tests-uses-wrong-bundle-path/37051/10
      run: xcodebuild test -scheme xcodes
